### ISSUE TITLE
Requiring unknown module "react-native/Libraries/Network/XHRInterceptor"

### ISSUE THREAD

**Issue by hsavit1** [infinitered/reactotron#420]
Hi,

I'm trying to run the reactoron on my React Native project on my android device. I did the setup and the adb reverse script. I'm still getting this error:

`Requiring unknown module "react-native/Libraries/Network/XHRInterceptor"`

Any ideas?

**Comment by skellock** [comment]
Which version of React Native are you using?

**Comment by hsavit1** [comment]
Wow quick response! Im at 34

**Comment by hsavit1** [comment]
@skellock

**Comment by skellock** [comment]
Ya, that interceptor didn't come around until 37 I believe.  You'll have to use an older version of `reactotron-react-native` or upgrade! =)

**Comment by jariwalabhavesh** [comment]
@skellock : which version of reactron is comparable with react-native version 34?? I can not update react-native due to some issue.

**Comment by skellock** [comment]
I’m not sure off the top of head. Check out the releases page. We probably list it there.

**Comment by cassianomon** [comment]
I am getting this error:

```
./node_modules/reactotron-react-native/dist/index.js
Module not found: Can't resolve 'react-native/Libraries/Network/XHRInterceptor' in 'app-path-here/node_modules/reactotron-react-native/dist'
```

package.json:


```
        "react": "16.8.6",
        "react-dom": "16.8.6",
        "react-native": "0.59.5",
        "react-redux": "^7.0.2",
        "react-router-dom": "^4.3.1",
        "react-scripts": "1.1.5",
        "redux": "^4.0.1",
        "redux-persist": "^5.10.0",
        "redux-saga": "^1.0.2"
```

**Comment by joshuayoes** [comment]
> Error: Unable to resolve module react-native/Libraries/Network/XHRInterceptor from C:\Users\yrpd2\Documents\Bhavdeep\Kids-Games\frontend\node_modules\reactotron-react-native\dist\index.esm.js: react-native/Libraries/Network/XHRInterceptor could not be found within the project or in these directories:
> 
> i have to use reactotron but show this error how to solve this please guide me

Can you mention a little bit more about your setup? The fact that this is the .esm.js build is a little curious to me.

**Comment by gurmiguel** [comment]
I'm facing the same issue, just tried to upgrade react native to version 0.79.0 and it started happening, looking at react native source, it seems the XHRInterceptor.js file is not there anymore

**Comment by Bhavdeep198** [comment]
i have to use react native latest version and reactotron this version i
have to use "reactotron-react-native": "^5.1.12"

can you guide me how can i setup

**Comment by NatalliaK** [comment]
same for me

"reactotron-react-native": "^5.1.12",
"react-native": "^0.79.0"

**Comment by ashrafayad** [comment]
**fast solution:**

in this file:
node_modules/reactotron-react-native/dist/index.esm.js

replace:
import XHRInterceptor from"react-native/Libraries/Network/XHRInterceptor"

to:
import XHRInterceptor from "react-native/src/private/inspector/XHRInterceptor.js"

**Comment by joshuayoes** [comment]
Thank you @ashrafayad for the solution! It sounds like we may need to find a way to look for that internal depending on the version of React Native loaded

**Comment by joshuayoes** [comment]
We rely on this path in our networking plugin 

https://github.com/infinitered/reactotron/blob/master/lib/reactotron-react-native/src/plugins/networking.ts

However we have an existing strategy of attempting to lazy load React Native internals if they existing in our trackGlobalErrors plugin, so perhaps we could try that here

https://github.com/infinitered/reactotron/blob/master/lib/reactotron-react-native/src/plugins/trackGlobalErrors.ts

**Comment by joshuayoes** [comment]
I don't have enough time this afternoon to test these PR changes yet, but if others affected by it want to give it a go until I have a chance to try, feel free to attempt to test plan and verify that it works. https://github.com/infinitered/reactotron/pull/1556

**Comment by thainguyen28vp** [comment]
Error: Unable to resolve module react-native/Libraries/Network/XHRInterceptor from /Users/nguyenthai/Desktop/rn/team_manager_app/node_modules/reactotron-react-native/dist/index.esm.js: react-native/Libraries/Network/XHRInterceptor could not be found within the project or in these directories:
I also had the same problem when upgrading react-native to 0.79.0

**Comment by joshuayoes** [comment]
Fix released in [reactotron-react-native@5.1.13](https://github.com/infinitered/reactotron/releases/tag/reactotron-react-native%405.1.13)

**Comment by joshuayoes** [comment]
> ```
> Error: Unable to resolve module react-native/Libraries/Network/XHRInterceptor from xxx\node_modules\reactotron-react-native\dist\index.esm.js: react-native/Libraries/Network/XHRInterceptor could not be found within the project or in these directories
> ```
> 
> Same here with React Native 0.79.1 and reactotron-react-native@5.1.13, **only** when setting up react-native-reanimated metro config.
> 
> ![Image](https://github.com/user-attachments/assets/4e28bdf4-26ab-48c9-80cc-ee7b5cda1ae0)
> 
> 

Would you mind sharing how you load your Reactotron configuration? Typically your app entrypoint.

**Comment by pinguluk** [comment]
Still not fixed https://github.com/infinitered/reactotron/issues/1554#issuecomment-2984771465

**Comment by joshuayoes** [comment]
Fix released in [reactotron-react-native@5.1.14](https://github.com/infinitered/reactotron/releases/tag/reactotron-react-native%405.1.14)!

**Comment by veb-ioki** [comment]
I checked [reactotron-react-native@5.1.14](https://github.com/infinitered/reactotron/releases/tag/reactotron-react-native%405.1.14) but still get the same error as before:
`Unable to resolve path to module 'react-native/Libraries/Network/XHRInterceptor`

(We are seeing the error since upgrade of RN from 0.74.2 to 0.79.4.)
