### ISSUE TITLE
Timeline stops responding to `clear`

### ISSUE THREAD

**Issue by scally** [infinitered/reactotron#422]
Sometimes, Reactotron stops responding to the `clear` button in the top-right corner for the Timeline view. Neither clicking `clear` at this point or Command-K will result in clearing the console.

I don't have a repro for this yet... sorry :(  I suspect it has something to do with sleep/resume of the computer, or using the developer menu inside the iOS simulator.

**Comment by skellock** [comment]
I've seen this as well.  Closing and restarting the app works, but I'd love to get to the bottom of this too.

My current working theory is that it's related to socket.io.  I've seen this on the command line as well going as far back as last year.

Thanks for filing this issue.

**Comment by rmevans9** [comment]
@skellock might be worth putting an `on('error'` callback and log out any error to the Reactotron timeline to help get to the bottom of this.

location: https://github.com/infinitered/reactotron/blob/master/packages/reactotron-core-server/src/index.js#L72

ref:  https://socket.io/docs/server-api/#event-error

**Comment by scientist1642** [comment]
Strangely, for me the Reactotron hangs if I call Reactotron.log(item1, item2) (i.e. with more than 1 parameter)

**Comment by skellock** [comment]
@scientist1642 oh? Are you using the 2.x version?

**Comment by scientist1642** [comment]
@skellock sorry, turns out I was passing object to Display.preview. Would be nice if it didn't hang though. Maybe fixed in 2.x? :) (I have 1.14.0)

**Comment by rmevans9** [comment]
Can anyone confirm that this still occurs in 2.x? I have not seen it occur in it yet.

**Comment by rmevans9** [comment]
Closing this for now since I have not heard about it happening in v2 and we did a lot to how communication between the client and server works. I am hopeful that works resolved this issue.

**Comment by scientist1642** [comment]
Sorry For the late answer. My problem was related to overriding console.log with reactotron which turned out to be a bad idea. 
Anyway I myself don't face such problem in v2 ⛳️
