### ISSUE TITLE
Always empty async storage in v2.0.0-beta.3

### ISSUE THREAD

**Issue by xipgroc** [infinitered/reactotron#669]
I've upgraded from v2.0.0-beta.2 to v2.0.0-beta.3 and, although reactotron correctly logs each async storage setItem(), when I click to see the data it is always empty, whereas with v2.0.0-beta.2 I can see all the data in each moment.

I'm using react-native 0.55.4, react-redux 5.0.7, react 16.3.1 and reactotron with reactotron-redux

**Comment by skellock** [comment]
oh noes!  thanks for the heads up!

**Comment by AMar4enko** [comment]
Not only async storage page is broken in beta.3, but also state subscription page.
Stays empty after adding subscription.

**Comment by skellock** [comment]
The state subscription bug is fixed up in `2.0.0-beta.4`.

**Comment by rmevans9** [comment]
Closing as this has been resolved. If you are seeing it still in beta 4+ please reopen.

**Comment by makenova** [comment]
Hi! 👋 
I'm using `reactotron-react-native@2.0.0-beta.5` and AsyncStorage is always empty. It displays the `Empty storage` message. It was reading the storage details just fine on the stable version before I upgraded.

**Comment by skellock** [comment]
Ya, async storage is still a problem.  This issue was a two-fer unfortunately.  I'll reopen this as a reminder to myself tomorrow.

**Comment by skellock** [comment]
She be fixed in beta 10!
